export const demoOrders = [
  {
    id: "demo-os-001",
    number: "OS-2026-0001",
    title: "Manutenção preventiva do servidor web",
    description: "Verificar alertas de disco e atualizar pacotes do servidor web.",
    status: "in_progress",
    priority: "high",
    category: "Servidor",
    sectorId: "sector-infra",
    sectorName: "Infraestrutura",
    environmentId: "demo-client-orion",
    environmentName: "Orion Saude",
    serviceId: "demo-service-diagnostic",
    serviceCode: "SRV-0001",
    serviceName: "Diagnóstico técnico",
    assetId: "srv-web-01",
    requesterName: "Operação",
    assignedTechnicianName: "Carla Mendes",
    servicePerformed: "Diagnóstico técnico",
    diagnosis: "Disco com alerta preventivo e pacotes pendentes.",
    attendanceNotes: "Janela combinada para execução fora do horário comercial."
  },
  {
    id: "demo-os-002",
    number: "OS-2026-0002",
    title: "Caixa com lentidão no atendimento",
    description: "Máquina do caixa 01 apresenta travamentos durante emissão de cupom.",
    status: "open",
    priority: "medium",
    category: "Desktop",
    sectorId: "sector-support-n1",
    sectorName: "Suporte N1",
    environmentId: "demo-client-alfa",
    environmentName: "Alfa Comercio",
    serviceId: "demo-service-diagnostic",
    serviceCode: "SRV-0001",
    serviceName: "Diagnóstico técnico",
    assetId: "ws-caixa-01",
    requesterName: "Frente de caixa",
    assignedTechnicianName: "Ana Ribeiro",
    servicePerformed: "Diagnóstico técnico",
    diagnosis: "Aguardando avaliação presencial."
  },
  {
    id: "demo-os-003",
    number: "OS-2026-0003",
    title: "Impressora do financeiro falhando",
    description: "Relatórios saem com falhas e manchas.",
    status: "waiting",
    priority: "medium",
    category: "Impressora",
    sectorId: "sector-financeiro",
    sectorName: "Financeiro",
    environmentId: "demo-client-beta",
    environmentName: "Beta Logistica",
    serviceId: "demo-service-printer",
    serviceCode: "SRV-0005",
    serviceName: "Manutenção de impressora",
    assetId: "manual-printer-financeiro",
    requesterName: "Financeiro",
    assignedTechnicianName: "Diego Santos",
    servicePerformed: "Manutenção de impressora",
    diagnosis: "Provável toner no fim e rolete com sujeira.",
    partsUsed: "Toner HP 58A x1"
  },
  {
    id: "demo-os-004",
    number: "OS-2026-0004",
    title: "Notebook da diretoria sem vídeo",
    description: "Usuário relata tela preta ao conectar dockstation.",
    status: "closed",
    priority: "high",
    category: "Notebook",
    sectorId: "sector-diretoria",
    sectorName: "Diretoria",
    environmentId: "demo-client-orion",
    environmentName: "Orion Saude",
    serviceId: "demo-service-network",
    serviceCode: "SRV-0004",
    serviceName: "Correção de rede",
    assetId: "nb-diretoria-01",
    requesterName: "Diretoria",
    assignedTechnicianName: "Bruno Lima",
    servicePerformed: "Correção de rede",
    diagnosis: "Cabo USB-C danificado.",
    attendanceNotes: "Substituído cabo e testado monitor externo.",
    closedAt: "2026-05-20T18:15:00.000Z"
  }
];
