import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowDownToLine, Boxes, CheckCircle2, Cpu, FileUp, History, PackagePlus, RefreshCw, Search, Settings2, ShieldAlert, Trash2, TriangleAlert, Warehouse, X } from "lucide-react";
import { createPartCategory, createPartInventoryItem, createPartInventoryMovement, deletePartCategory, fetchPartCategories, fetchPartInventoryItem, fetchPartsInventory, importPartsInvoice, syncPartsFromAssets, updatePartInventoryItem } from "../../api.js";
import "./partsInventory.css";

const EMPTY_PART = { name: "", category: "", brand: "", model: "", internalCode: "", manufacturerPartNumber: "", serialNumber: "", macAddress: "", location: "", quantity: 0, minimumStock: 0, unitPrice: 0, unit: "un", conditionStatus: "new", notes: "", active: true };
const MOVEMENT_LABELS = { receipt: "Entrada", consumption: "Consumo", return: "Retorno", adjustment: "Ajuste de saldo", assignment: "Designação", unassignment: "Desvinculação" };
const INVENTORY_LABELS = { available: "Disponível", in_use: "Em uso" };

function PartForm({ part, categories, saving, onClose, onSave }) {
  const [form, setForm] = useState(part ? { ...EMPTY_PART, ...part } : EMPTY_PART);
  const set = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.type === "number" ? Number(event.target.value) : event.target.value }));
  return <div className="parts-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <form className="parts-form-modal" onSubmit={(event) => { event.preventDefault(); onSave(form); }}>
      <header><div><span>Cadastro rastreável</span><h2>{part ? "Editar peça" : "Nova peça"}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar"><X /></button></header>
      <div className="parts-form-grid">
        <label className="wide">Nome<input value={form.name} onChange={set("name")} required /></label>
        <label>Categoria<select value={form.category || ""} onChange={set("category")} required><option value="">Selecione</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select></label>
        <label>Fabricante<input value={form.brand || ""} onChange={set("brand")} /></label><label>Modelo<input value={form.model || ""} onChange={set("model")} /></label>
        <label>Código interno<input value={form.internalCode || ""} onChange={set("internalCode")} /></label><label>Part number<input value={form.manufacturerPartNumber || ""} onChange={set("manufacturerPartNumber")} /></label>
        <label>Número de série<input value={form.serialNumber || ""} onChange={set("serialNumber")} /></label><label>MAC<input value={form.macAddress || ""} onChange={set("macAddress")} /></label>
        <label>Localização<input value={form.location || ""} onChange={set("location")} placeholder="Almoxarifado / prateleira" /></label><label>Condição<select value={form.conditionStatus} onChange={set("conditionStatus")}><option value="new">Nova</option><option value="used">Usada</option><option value="refurbished">Recondicionada</option><option value="damaged">Danificada</option></select></label>
        {!part ? <label>Estoque inicial<input type="number" min="0" step="1" value={form.quantity} onChange={set("quantity")} /></label> : null}<label>Estoque mínimo<input type="number" min="0" step="1" value={form.minimumStock} onChange={set("minimumStock")} /></label>
        <label>Valor unitário<input type="number" min="0" step="0.01" value={form.unitPrice} onChange={set("unitPrice")} /></label><label>Unidade<input value={form.unit || "un"} onChange={set("unit")} /></label>
        <label className="wide">Observações<textarea rows="3" value={form.notes || ""} onChange={set("notes")} /></label>
      </div>
      <footer><button type="button" className="secondary-action" onClick={onClose}>Cancelar</button><button type="submit" className="primary-action" disabled={saving}>{saving ? "Salvando..." : "Salvar peça"}</button></footer>
    </form>
  </div>;
}

function CategoryModal({ categories, saving, onClose, onCreate, onDelete }) {
  const [name, setName] = useState("");
  return <div className="parts-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}>
    <section className="parts-form-modal parts-category-modal" role="dialog" aria-modal="true" aria-labelledby="parts-category-title">
      <header><div><span>Configuração do inventário</span><h2 id="parts-category-title">Categorias de peças</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar"><X /></button></header>
      <form className="parts-category-create" onSubmit={(event) => { event.preventDefault(); if (name.trim()) onCreate(name.trim()).then(() => setName("")); }}><label>Nova categoria<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Refrigeração" /></label><button className="primary-action" disabled={saving || !name.trim()}>Adicionar</button></form>
      <div className="parts-category-list">{categories.map((category) => <div key={category.id}><span style={{ "--category-color": category.color }} /><strong>{category.name}</strong><button type="button" className="icon-button danger" onClick={() => onDelete(category.id)} aria-label={`Remover ${category.name}`}><Trash2 size={15} /></button></div>)}</div>
    </section>
  </div>;
}

function PartInspector({ part, devices, serviceOrders, permissions, saving, onClose, onEdit, onMove }) {
  const [movement, setMovement] = useState({ movementType: "consumption", quantity: 1, assetId: "", serviceOrderId: "", notes: "" });
  const assetName = (id) => devices.find((item) => item.id === id)?.alias || devices.find((item) => item.id === id)?.hostname || id;
  return <aside className="part-inspector">
    <header><div><span>{part.category || "Peça"}</span><h3>{part.name}</h3></div><button type="button" className="icon-button" onClick={onClose} aria-label="Fechar"><X /></button></header>
    <div className="part-inspector-body">
      {part.discrepancyStatus !== "ok" ? <div className="part-discrepancy"><ShieldAlert /><div><strong>Incongruência detectada</strong><span>{part.discrepancyDetails?.reason || "O agente identificou uma mudança de hardware sem movimentação ou OS correspondente."}</span></div></div> : null}
      <dl className="part-identity"><div><dt>Situação</dt><dd>{INVENTORY_LABELS[part.inventoryState] || part.inventoryState}</dd></div><div><dt>Quantidade</dt><dd>{part.quantity} {part.unit}</dd></div><div><dt>ID da peça</dt><dd>{part.internalCode || part.id}</dd></div><div><dt>Série / MAC</dt><dd>{part.serialNumber || part.macAddress || "—"}</dd></div><div><dt>Localização</dt><dd>{part.location || "Não informada"}</dd></div><div><dt>Ativo atual</dt><dd>{part.assignedAssetId ? assetName(part.assignedAssetId) : "Não vinculado"}</dd></div>{part.supplierName ? <div className="wide"><dt>Fornecedor</dt><dd>{part.supplierName}</dd></div> : null}</dl>
      {permissions.update && part.source !== "agent" ? <button type="button" className="secondary-action" onClick={onEdit}>Editar cadastro</button> : null}
      {permissions.moveStock && part.inventoryState === "available" ? <form className="part-movement-form" onSubmit={(event) => { event.preventDefault(); onMove(movement); }}><h4><ArrowDownToLine size={16} /> Movimentar estoque</h4><div><label>Operação<select value={movement.movementType} onChange={(event) => setMovement((current) => ({ ...current, movementType: event.target.value }))}>{Object.entries(MOVEMENT_LABELS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Quantidade<input type="number" min="1" step="1" value={movement.quantity} onChange={(event) => setMovement((current) => ({ ...current, quantity: Number(event.target.value) }))} /></label></div><label>Ativo<select value={movement.assetId} onChange={(event) => setMovement((current) => ({ ...current, assetId: event.target.value }))}><option value="">Sem ativo</option>{devices.map((item) => <option key={item.id} value={item.id}>{assetName(item.id)}</option>)}</select></label><label>Ordem de Serviço<select value={movement.serviceOrderId} onChange={(event) => setMovement((current) => ({ ...current, serviceOrderId: event.target.value }))}><option value="">Sem OS</option>{serviceOrders.filter((item) => !item.closedAt && item.status !== "closed").map((item) => <option key={item.id} value={item.id}>{item.number} · {item.title}</option>)}</select></label><label>Observação<input value={movement.notes} onChange={(event) => setMovement((current) => ({ ...current, notes: event.target.value }))} placeholder="Motivo, lote ou destino" /></label><button type="submit" className="primary-action" disabled={saving}>{saving ? "Registrando..." : "Registrar movimentação"}</button></form> : null}
      <section className="part-history"><h4><History size={16} /> Histórico da peça</h4>{part.movements?.length ? <ol>{part.movements.map((item) => <li key={item.id}><span className={`movement-icon type-${item.movementType}`}>{["receipt", "return"].includes(item.movementType) ? "+" : "−"}</span><div><strong>{MOVEMENT_LABELS[item.movementType] || item.movementType} · {item.quantity} {part.unit}</strong><small>{new Date(item.createdAt).toLocaleString("pt-BR")} · saldo {item.previousQuantity} → {item.resultingQuantity}</small>{item.serviceOrderNumber ? <em>OS {item.serviceOrderNumber}</em> : null}{item.assetId ? <em>{assetName(item.assetId)}</em> : null}{item.notes ? <p>{item.notes}</p> : null}</div></li>)}</ol> : <p>Nenhuma movimentação registrada.</p>}</section>
    </div>
  </aside>;
}

export default function PartsInventoryPage({ token, notify, devices = [], serviceOrders = [], permissions = {} }) {
  const [parts, setParts] = useState([]), [categories, setCategories] = useState([]), [selected, setSelected] = useState(null), [formPart, setFormPart] = useState(undefined), [categoryModal, setCategoryModal] = useState(false), [search, setSearch] = useState(""), [inventoryState, setInventoryState] = useState(""), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  const fileInput = useRef(null), reconciled = useRef(false);
  const load = useCallback(async () => { setLoading(true); try { const [partsData, categoriesData] = await Promise.all([fetchPartsInventory(token, { search, inventoryState }), fetchPartCategories(token)]); setParts(partsData.parts || []); setCategories(categoriesData.categories || []); } catch (error) { notify?.(error.message, "danger"); } finally { setLoading(false); } }, [inventoryState, notify, search, token]);
  useEffect(() => { const timer = setTimeout(load, search ? 220 : 0); return () => clearTimeout(timer); }, [load, search]);
  useEffect(() => { if (!permissions.reconcileHardware || reconciled.current) return; reconciled.current = true; syncPartsFromAssets(token).then(({ summary }) => { if (summary.created || summary.discrepancies) load(); }).catch((error) => notify?.(error.message, "danger")); }, [load, notify, permissions.reconcileHardware, token]);
  const summary = useMemo(() => ({ catalog: parts.length, available: parts.filter((item) => item.inventoryState === "available").reduce((sum, item) => sum + item.quantity, 0), inUse: parts.filter((item) => item.inventoryState === "in_use").length, discrepancies: parts.filter((item) => item.discrepancyStatus !== "ok").length }), [parts]);
  async function openPart(id) { try { const data = await fetchPartInventoryItem(token, id); setSelected(data.part); } catch (error) { notify?.(error.message, "danger"); } }
  async function savePart(payload) { setSaving(true); try { const data = formPart?.id ? await updatePartInventoryItem(token, formPart.id, payload) : await createPartInventoryItem(token, payload); setFormPart(undefined); setSelected(data.part); notify?.("Peça salva no inventário.", "ok"); await load(); } catch (error) { notify?.(error.message, "danger"); } finally { setSaving(false); } }
  async function movePart(payload) { setSaving(true); try { const data = await createPartInventoryMovement(token, selected.id, payload); setSelected(data.part); notify?.("Movimentação registrada no histórico.", "ok"); await load(); } catch (error) { notify?.(error.message, "danger"); } finally { setSaving(false); } }
  async function addCategory(name) { setSaving(true); try { await createPartCategory(token, { name }); notify?.("Categoria adicionada.", "ok"); await load(); } catch (error) { notify?.(error.message, "danger"); } finally { setSaving(false); } }
  async function removeCategory(id) { setSaving(true); try { await deletePartCategory(token, id); notify?.("Categoria removida da lista.", "ok"); await load(); } catch (error) { notify?.(error.message, "danger"); } finally { setSaving(false); } }
  async function reconcile() { setSaving(true); try { const { summary: result } = await syncPartsFromAssets(token); notify?.(`${result.created} peça(s) descoberta(s); ${result.discrepancies} incongruência(s).`, result.discrepancies ? "warning" : "ok"); await load(); } catch (error) { notify?.(error.message, "danger"); } finally { setSaving(false); } }
  async function importInvoice(file) { if (!file) return; setSaving(true); try { const xml = await file.text(); const { summary: result } = await importPartsInvoice(token, xml); notify?.(`NF-e importada: ${result.created} cadastro(s) e ${result.merged} saldo(s) atualizados.`, "ok"); await load(); } catch (error) { notify?.(error.message, "danger"); } finally { setSaving(false); if (fileInput.current) fileInput.current.value = ""; } }
  return <section className={`parts-inventory-page ${selected ? "has-inspector" : ""}`}>
    <div className="parts-inventory-main">
      <header className="parts-page-heading"><div><span><Boxes size={16} /> Controle patrimonial e de manutenção</span><h2>Inventário de Peças</h2><p>Disponibilidade, hardware em uso e divergências técnicas em uma única trilha.</p></div><div className="parts-heading-actions">{permissions.importInvoice ? <><input ref={fileInput} className="visually-hidden" type="file" accept=".xml,application/xml,text/xml" onChange={(event) => importInvoice(event.target.files?.[0])} /><button type="button" className="secondary-action" onClick={() => fileInput.current?.click()} disabled={saving}><FileUp size={17} /> Importar NF-e</button></> : null}{permissions.create ? <button type="button" className="primary-action" onClick={() => setFormPart(null)}><PackagePlus size={17} /> Cadastrar peça</button> : null}</div></header>
      {summary.discrepancies ? <button type="button" className="parts-alert-banner" onClick={() => setInventoryState("in_use")}><ShieldAlert /><span><strong>{summary.discrepancies} incongruência(s) de hardware aguardando conferência</strong>Alterações coletadas pelo agente sem histórico de OS ou movimentação correspondente.</span><span>Revisar</span></button> : null}
      <div className="parts-summary"><div><Boxes /><span>Itens rastreados<strong>{summary.catalog}</strong></span></div><div><Warehouse /><span>Unidades disponíveis<strong>{summary.available}</strong></span></div><div><Cpu /><span>Componentes em uso<strong>{summary.inUse}</strong></span></div><div className={summary.discrepancies ? "warning" : ""}>{summary.discrepancies ? <TriangleAlert /> : <CheckCircle2 />}<span>Incongruências<strong>{summary.discrepancies}</strong></span></div></div>
      <div className="parts-toolbar"><label className="parts-search"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar peça, código, série, part number, MAC ou fornecedor" /></label><select value={inventoryState} onChange={(event) => setInventoryState(event.target.value)}><option value="">Todo o inventário</option><option value="available">Peças disponíveis</option><option value="in_use">Peças em uso</option></select>{permissions.reconcileHardware ? <button type="button" className="secondary-action" onClick={reconcile} disabled={saving}><RefreshCw size={16} /> Conciliar ativos</button> : null}{permissions.manageCategories ? <button type="button" className="icon-button parts-settings-button" onClick={() => setCategoryModal(true)} aria-label="Configurar categorias"><Settings2 /></button> : null}</div>
      {loading ? <p className="dashboard-empty-state">Atualizando o inventário...</p> : parts.length ? <div className="parts-grid">{parts.map((part) => <button type="button" key={part.id} className={`part-card stock-${part.stockStatus} state-${part.inventoryState} ${part.discrepancyStatus !== "ok" ? "has-discrepancy" : ""}`} onClick={() => openPart(part.id)}><span className="part-card-icon">{part.inventoryState === "in_use" ? <Cpu /> : <Boxes />}</span><div><span className="part-card-kicker"><small>{part.category || "Sem categoria"}</small><b>{INVENTORY_LABELS[part.inventoryState] || "Disponível"}</b></span><strong>{part.name}</strong><em>{[part.brand, part.model].filter(Boolean).join(" · ") || part.internalCode || "Cadastro técnico"}</em>{part.discrepancyStatus !== "ok" ? <span className="part-card-warning"><ShieldAlert size={13} /> Conferência necessária</span> : null}</div><span className="part-stock"><strong>{part.quantity}</strong>{part.unit}<small>{part.inventoryState === "in_use" ? "Instalada" : part.stockStatus === "out" ? "Sem estoque" : part.stockStatus === "low" ? "Reposição necessária" : "Disponível"}</small></span></button>)}</div> : <div className="parts-empty"><Boxes size={34} /><strong>Nenhuma peça encontrada</strong><span>Cadastre um item, importe uma NF-e ou concilie os ativos monitorados.</span></div>}
    </div>
    {selected ? <PartInspector part={selected} devices={devices} serviceOrders={serviceOrders} permissions={permissions} saving={saving} onClose={() => setSelected(null)} onEdit={() => setFormPart(selected)} onMove={movePart} /> : null}
    {formPart !== undefined ? <PartForm part={formPart} categories={categories} saving={saving} onClose={() => setFormPart(undefined)} onSave={savePart} /> : null}
    {categoryModal ? <CategoryModal categories={categories} saving={saving} onClose={() => setCategoryModal(false)} onCreate={addCategory} onDelete={removeCategory} /> : null}
  </section>;
}
